services:
  tg_poster:
    build: .
    container_name: tg_poster
    ports:
      - "7777:7777"
    volumes:
      - .:/app
      - "C:/tg_media:/app/media"
    environment:
      - BOT_TOKEN=${BOT_TOKEN:-}
      - TZ=${TZ:-Asia/Yekaterinburg}
      - MEDIA_PATH=${MEDIA_PATH:-/app/media}
    restart: unless-stopped
