version: '3.8'
services:
  tg_poster:
    build: .
    container_name: tg_poster
    ports:
      - "7777:7777"
    volumes:
    - .:/app
    - "C:/tg_media:/app/media"
    environment:
      - BOT_TOKEN=7645199777:AAGsqPXgyd-IWPTX-S7sAOPPDydSkXwmXVI
      - TZ=Asia/Yekaterinburg
    restart: unless-stopped 
